<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Weather-app</title>
    <style>
        body {
            background-image: url('../../../public/images/RS5V.gif');
            background-repeat: repeat;
        }
    </style>
</head>

<body>
    <br>
    <br>
    <br>

    <form method="POST" action="index/search">
        <div class="container">

            <div class="row height d-flex justify-content-center align-items-center">

                <div class="col-md-6">

                    <div class="search">
                        <i class="fa fa-search"></i>
                        <input type="text" class="form-control" name="city" placeholder="Enter city name">
                        <br>
                        <label for="choices">Choose a option:</label>

                        <select name="type" id="option">
                            <option value="/current.json">Current weather</option>
                            <option value="/forecast.json">Forecast</option>
                            <option value="/history.json">History</option>
                            <option value="/timezone.json">Time Zone</option>
                            <option value="/sports.json">Sports</option>
                            <option value="/astronomy.json">Astronomy</option>
                           
                        </select>
                        <button type="submit" class="btn btn-primary">Search</button>

                    </div>
                </div>

            </div>
        </div>
    </form>
</body>

</html>