<?php
echo "  <style>
        body {
            background-image: url('../../../public/images/RS5V.gif');
            background-repeat: repeat;
        }
    </style>";
?>
<section class="vh-100" style="background-color: #f5f6f7;">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-md-10 col-lg-8 col-xl-6">
                <h1>
                    <center>SPORTS</center>
                </h1>
                <div class="card bg-dark text-white" style="border-radius: 40px;">
                    <div class="bg-image" style="border-radius: 35px;">
                        <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-weather/draw1.webp"
                         class="card-img" alt="weather" />
                        <div class="mask" style="background-color: rgba(190, 216, 232, .5);"></div>
                    </div>
                    <div class="card-img-overlay text-dark p-5">
                        <h4 class="mb-0"><?php
                                            foreach ($data as $key => $value) {
                                                echo "->" . $key;
                                                echo "<br>";
                                            }
                                            ?></h4>

                    </div>
                </div>

            </div>
        </div>
    </div>
</section>