<?php

echo "  <style>
        body {
            background-image: url('../../../public/images/RS5V.gif');
            background-repeat: repeat;
        }
    </style>";
?>

<section class="vh-100" style="background-color:#343a40;">
  <div class="container py-5 h-100">
    <h1>
      <center>Time-Zone</center>
    </h1>
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-md-8 col-lg-6 col-xl-4">

        <div class="card" style="color: #4B515D; border-radius: 35px;">
          <div class="card-body p-4">

            <div class="d-flex">
              <h6 class="flex-grow-1"><?php
                                      echo $data['location']['name'];
                                      ?></h6>
              <h6><?php
                  echo $data['location']['localtime'];
                  ?></h6>
            </div>

            <div class="d-flex flex-column text-center mt-5 mb-4">
              <h6 class="display-4 mb-0 font-weight-bold" style="color: #1C2331;"><?php
                                                                                  echo $data['location']['name'];
                                                                                  ?></h6>
              <h6><?php
                  echo $data['location']['tz_id'];
                  ?></h6>
            </div>

            <div class="d-flex align-items-center">
              <div class="flex-grow-1" style="font-size: 1rem;">
                <div><i class="fas fa-wind fa-fw" style="color: #868B94;"></i> <span class="ms-1"><?php
                echo $data['location']['lat'];
                                                                                                  ?>
                  </span></div>
                <div><i class="fas fa-tint fa-fw" style="color: #868B94;"></i> <span class="ms-1"><?php
                 echo $data['location']['lon'];
                                                                                                  ?></span>
                </div>
                <div><i class="fas fa-sun fa-fw" style="color: #868B94;"></i> <span class="ms-1"><?php
                  echo $data['location']['region'];
                                                                                                  ?></span>
                </div>
                <div><i class="fas fa-sun fa-fw" style="color: #868B94;"></i> <span class="ms-1"><?php
                echo $data['location']['country'];
                                                                                                  ?></span>
                </div>
              </div>
              <div>
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-weather/ilu1.webp" width="100px">
              </div>
            </div>

          </div>
        </div>

      </div>
    </div>

  </div>
</section>